[package]
name = "iced_testing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.13.1"
rand = "0.9.0"
uuid = {version = "1.12.1", features = ["v4"]}
